### PR TITLE
(WIP) Clean up

### PR DESCRIPTION
**Pull request by curbengh**
the Grunt-ed/Babel-ed lib/ are not functioning yet. I don't know how to proceed further...

### CODE REVIEW

**Comment by curbengh** [comment]
Possibly duplicate of #23

**Comment by curbengh** [comment]
I'll leave removal of babel and grunt to @segayuu ,
https://github.com/hexojs/hexo-inject/pull/23
https://github.com/hexojs/hexo-inject/pull/27
https://github.com/hexojs/hexo-inject/pull/28
https://github.com/hexojs/hexo-inject/pull/29

**Comment by segayuu** [comment]
[ES Module is implemented as an experimental future in node.js.](https://nodejs.org/api/esm.html
)
This is a feature currently under development, and its behavior with babel@6 has changed (it has been fixed in bebel@7).
Therefore, I think it would be difficult to remove babel@6 with ES Module.

**Comment by segayuu** [comment]
I decided to require extensive coding to remove Babel and switched #28 to Issue #32.
It's not a problem that you can deal with by yourself, so it would be helpful if you could help :)

**Comment by curbengh** [comment]
I'll see what I can do. In the meantime, I close this in favor of yours.

**Pull request closed without merging**
